### ISSUE TITLE
Click animation stops when not logged in

### ISSUE THREAD

**Issue by josehfp** [fmilani/contatempo#13]
If you try to click in "Config" when not logged in, the click animation(inside buttons) stop working properly.
![image](https://cloud.githubusercontent.com/assets/15706217/26560047/dede0ea0-4489-11e7-8900-76202b819dfc.png)

**Comment by fmilani** [comment]
Thanks for reporting this issue @josehfp.
I just made a commit addressing this issue so I'm closing it. Feel free to reopen if you ever run into the same problem.
